services:
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "3000:3000"
    networks:
      - nodejs
  
  mongodb:
    image: mongo:6.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nodejs
networks:
  nodejs:
    driver: bridge
volumes:
  mongodb_data: