services:
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "3000:3000"
    networks:
      - nodejs
  
  mongodb:
    image: mongo:6.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nodejs
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:9.0.0
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:9.0.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    networks:
      - nodejs

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
networks:
  nodejs:
    driver: bridge
volumes:
  mongodb_data: